//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FastScanNMeasureCN.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_OLE_INIT_FAILED             100
#define IDS_MEASPOINTTOPOINT            101
#define IDS_MEASPOINTTOLINE             102
#define IDS_GRIDDSCR                    103
#define IDS_GRIDMEASTITLECOL1           103
#define IDS_GRIDFEATURE                 104
#define IDS_GRIDMEASTITLECOL2           104
#define IDS_GRIDMEASURED                105
#define IDS_GRIDMEASTITLECOL3           105
#define IDS_GRIDTOLERANCE               106
#define IDS_GRIDMEASTITLECOL4           106
#define IDS_MEASDEV                     107
#define IDS_MSGCAMNOTCON                108
#define IDS_MSGUWCNA                    109
#define IDS_MEASLINETOLINEANGLE         110
#define IDS_MEASLINETOLINEDIST          111
#define IDS_MEASCIRCLERAD               112
#define IDS_MEASCIRCLE                  112
#define IDS_MEASCIRCLEDIA               113
#define IDS_MEASCIRCLERNDERROR          114
#define IDS_MEASDISTBET2OBJ             115
#define IDS_SAVEMODFILE                 116
#define IDS_MEASLINETOCIRCLE            117
#define IDS_MEASSLOTTOSLOT              118
#define IDS_MEASPOINTTOCIRCLE           119
#define IDS_MEASPOINTTOSLOT             120
#define IDS_SEL_CLKD_POINT              121
#define IDS_SEL_CORNER_POINT            122
#define IDS_SEL_LINE_INT_POINT          123
#define IDS_SEL_LINE_MIDPOINT           124
#define IDS_SEL_EDGE_LINE               125
#define IDS_SEL_CONSTR_LINE             126
#define IDS_SEL_EDGE_CIRCLE             127
#define IDS_STRING128                   128
#define IDR_MAINFRAME                   128
#define IDS_SEL_SLOT                    129
#define IDS_SEL_ARC_EDGE                130
#define IDS_SEL_ELLIPSE_EDGE            131
#define IDS_SEL_RECT_EDGE               132
#define IDS_SEL_LINE_AUTO_DETECT        133
#define IDS_SEL_CLKD_POLYGON            134
#define IDS_ZOOM_LEVEL                  135
#define IDS_READY                       136
#define IDS_LINE_DONE                   137
#define IDS_CIRCLE_DONE                 138
#define IDS_ELLIPSE_DONE                139
#define IDS_SLOT_DONE                   140
#define IDS_RECT_DONE                   141
#define IDS_POLY_DONE                   142
#define IDS_ARC_DONE                    143
#define IDS_MEASRECT                    144
#define IDS_MEASPOINTPOS                145
#define IDS_MEASLINEPARAMS              146
#define IDS_MEASPOLY_AREA               147
#define IDS_CIRCLE_FAIL                 148
#define IDS_SLOT_FAIL                   149
#define IDS_RECT_FAIL                   150
#define IDS_SHAPE_DELETED               151
#define IDS_SET_WORK_ZEROX              152
#define IDS_SET_WORK_ZEROY              153
#define IDS_SHIFT_WORK_ZEROXY           154
#define IDS_SHIFT_WORK_ZERO_ANGLE       155
#define IDS_SET_FOCUS                   156
#define IDS_LABEL_HORZ_DIST             157
#define IDS_LABEL_VERT_DIST             158
#define IDS_LABEL_DIST_LINEAR           159
#define IDS_LABEL_BASELINE              160
#define IDS_LABEL_RAD                   161
#define IDS_LABEL_DIA                   162
#define IDS_LABEL_XY_COORDS             163
#define IDS_LABEL_TEXT                  164
#define IDS_LABEL_EDIT                  165
#define IDS_SEL_CONSTR_POINT            166
#define IDS_MEASPOINTTORECT             167
#define IDS_MEASPOINTTOPOLY             168
#define IDS_MEASLINETORECT              169
#define IDS_MEASLINETOSLOT              170
#define IDS_MEASLINETOPOLY              171
#define IDS_MEASPOLYTOPOLY              172
#define IDS_MSG_SHAPE_SEL_CANCEL        173
#define IDS_SET_WORK_PATTERN            174
#define IDS_SHIFT_WORK_ZERO_DONE        175
#define IDS_SET_AXES_DONE               176
#define IDS_MEASCIRCLETOCIRCLE          177
#define IDS_MEASLINETOCIRCLEFAR         178
#define IDS_MEASLINETOCIRCLENEAR        179
#define IDS_MEASLINETOARCFAR            180
#define IDS_MEASLINETOARCNEAR           181
#define IDS_MEASCIRCLETOARCCTR          182
#define IDS_MEASARCTOARCCTR             183
#define IDS_MEASLINETOARCCTR            184
#define IDS_GRIDMEASTITLECOL6           185
#define IDS_WINDOW_CAD_ALIGNED          186
#define IDS_LINE_CUT                    187
#define IDS_LINE_EXTEND                 188
#define IDS_SEL_LINE_EXTEND             189
#define IDS_SEL_LINE_CUT                190
#define IDS_ARC_FAIL                    191
#define IDS_SEL_CLKD_ELLIPSE            192
#define IDS_SEL_CLKD_SPLINE             193
#define IDS_MEASDIST_PARALLEL_LINES     194
#define IDS_LENGTH                      195
#define IDS_WIDTH                       196
#define IDS_ANGLE                       197
#define IDS_AUTO_FIND                   198
#define IDS_CLICKED                     199
#define IDS_CONSTRUCT                   200
#define IDS_MEAS                        201
#define IDS_COORD                       202
#define IDS_HEIGHT                      203
#define IDS_DIST                        204
#define IDS_MEASLINETOARC               205
#define IDS_MEASCIRCLETOARC             206
#define IDS_MEASARCTOARC                207
#define IDS_INVALID                     208
#define IDS_FASTSCANNMEASURE            209
#define IDS_LICENCE_EXPIRED             210
#define IDS_APP_RUNNING                 211
#define IDS_IMAGE_NOT_FOUND             212
#define IDS_CALIB_NOT_CENTERED          213
#define IDS_INVALID_VALUES              214
#define IDS_CAMPARAMS_LINERATE_CHECK    215
#define IDS_CAMPARAMS_EXPTIME_CHECK     216
#define IDS_INSP_TIMELAPSE_CHECK        217
#define IDS_INSP_JOBSET_NUM_CHECK       218
#define IDS_DLG_DELETEJOB_CHK_SELECTBEFOREDELETE 219
#define IDS_DLG_DELETEJOB_CHK_CONFIRMDELETE 220
#define IDS_DLG_DELETEJOB_CHK_CANNOTDELETEJOB 221
#define IDS_DLG_DELETEJOB_HASBEENDELETED 222
#define IDS_DLG_DELETEJOB_COULDNOTDELETE 223
#define IDS_DLG_JOB_ASK_LOADSETTING     224
#define IDS_DLG_JOB_SELECTED            225
#define IDS_DLG_SET_EXP_TIME            226
#define IDS_COM_PORT_NOT_OPEN           227
#define IDS_CPORT_NOT_AVAILABLE         227
#define IDS_DLG_MEAS_AVG_DIST           228
#define IDS_MEASPOINTTOARC              229
#define IDS_DLG_MEAS_ARC_START_ANGLE    230
#define IDS_DLG_MEAS_ARC_END_ANGLE      231
#define IDS_DLG_MEAS_ARC_LENGTH         232
#define IDS_DLG_MEAS_ARC_INCLINATION_ANGLE 233
#define IDS_MEASARC                     234
#define IDS_MSGCAMRECONNECT             235
#define IDS_EDIT_SHAPE                  236
#define IDS_LOAD_MASTER_IMAGE           237
#define IDS_EXPORT_DXF                  238
#define IDS_GRIDMEASTITLECOL5           239
#define IDS_MSGSECURITYDONGLE           240
#define IDS_IMAGE_ENHANCEMENT           241
#define IDS_SETTING_COLOR               242
#define IDS_CALIB_ROWS_OF_CIRCLES       243
#define IDS_CALIB_COLS_OF_CIRCLES       244
#define IDS_CALIB_DIAMETER_OF_CIRCLE    245
#define IDS_CALIB_DIST_BET_TWO_CIRCLES  246
#define IDS_IMG_ENHC_GRAY_STRETCH       247
#define IDS_IMG_ENHC_RESET              248
#define IDS_IMG_ENHC_APPLY_EDGE_DETECTION 249
#define IDS_CALIBRATION_ABORTED         250
#define IDS_CALIB_THREE_CIRCLES_CHCK1   251
#define IDS_CALIB_THREE_CIRCLES_CHCK2   252
#define IDS_CALIB_MANUAL_XY             253
#define IDS_CALIB_THREE_CIRCLES_CHCK    254
#define IDS_DLGINSPPARAMS               255
#define IDS_DLGINSPPARAMS_SHAPESIZESELECTION 256
#define IDS_DLGINSPPARAMS_SHAPESIZESELECTION_MIN 257
#define IDS_DLGINSPPARAMS_SHAPESIZESELECTION_MAX 258
#define IDS_DLGINSPPARAMS_SEGMENTCONTOURPARAMS 259
#define IDS_DLGINSPPARAMS_SEGMENTCONTOURPARAMS_MODE 260
#define IDS_DLGINSPPARAMS_SEGMENTCONTOURPARAMS_SMOOTHNESS 261
#define IDS_DLGINSPPARAMS_SEGMENTCONTOURPARAMS_MAXLINEDIST1 262
#define IDS_DLGINSPPARAMS_SEGMENTCONTOURPARAMS_MAXLINEDIST2 263
#define IDS_DLGINSPPARAMS_ALGOPARAMS    264
#define IDS_DLGINSPPARAMS_ALGOPARAMS_ALGO 265
#define IDS_DLGINSPPARAMS_ALGOPARAMS_MAXNUMPNTS 266
#define IDS_DLGINSPPARAMS_ALGOPARAMS_CLIPINGPNTS 267
#define IDS_DLGINSPPARAMS_ALGOPARAMS_ITERATIONS 268
#define IDS_DLGINSPPARAMS_ALGOPARAMS_CLIPPINGFACTOR 269
#define IDS_DLGINSPPARAMS_FITLINEPARAMS 270
#define IDS_DLGINSPPARAMS_UNIONCOLINEARLINES 271
#define IDS_DLGINSPPARAMS_UNIONCOLINEARLINES_MAXDISTABS 272
#define IDS_DLGINSPPARAMS_UNIONCOLINEARLINES_MAXDISTREL 273
#define IDS_DLGINSPPARAMS_UNIONCOLINEARLINES_MAXSHIFT 274
#define IDS_DLGINSPPARAMS_FITCIRCLEPARAMS 275
#define IDS_DLGINSPPARAMS_UNIONCOCIRCULARCIRCLES 276
#define IDS_DLGINSPPARAMS_UNIONCOCIRCULARCIRCLES_MAXANGLEDIFF 277
#define IDS_DLGINSPPARAMS_UNIONCOCIRCULARCIRCLES_MAXOVERLAP 278
#define IDS_DLGINSPPARAMS_UNIONCOCIRCULARCIRCLES_MAXTANGENTANGLE 279
#define IDS_DLGINSPPARAMS_UNIONCOCIRCULARCIRCLES_MAXDIST 280
#define IDS_DLGINSPPARAMS_UNIONCOCIRCULARCIRCLES_MAXRADIUSDIFF 281
#define IDS_DLGINSPPARAMS_UNIONCOCIRCULARCIRCLES_MAXCENTERDIST 282
#define IDS_DLGINSPPARAMS_UNIONCOCIRCULARCIRCLES_ITERATIONS 283
#define IDS_DLGINSPPARAMS_FITRECTPARAMS 284
#define IDS_DLGINSPPARAMS_UNIONADJACENTCONTOURS 285
#define IDS_DLGINSPPARAMS_UNIONADJACENTCONTOURS_MAXABSDIST 286
#define IDS_DLGINSPPARAMS_UNIONADJACENTCONTOURS_MAXRELDIST 287
#define IDS_DLGINSPPARAMS_FITELLIPSEPARAMS 288
#define IDS_DLGINSPPARAMS_MODELPARAMS   289
#define IDS_DLGINSPPARAMS_MODELPARAMS_CONTRAST 290
#define IDS_DLGINSPPARAMS_MODELPARAMS_MINCONTRAST 291
#define IDS_DLGINSPPARAMS_MODELPARAMS_REDUCTIONFACTOR 292
#define IDS_DLGINSPPARAMS_INSPMODELPARAMS 293
#define IDS_DLGINSPPARAMS_INSPMODELPARAMS_MINCONTRAST 294
#define IDS_DLGINSPPARAMS_INSPMODELPARAMS_MAXCONTRAST 295
#define IDS_DLGINSPPARAMS_INSPMODELPARAMS_CONTRASTTHRESH 296
#define IDS_DLGINSPPARAMS_DETECTMODELPARAMS 297
#define IDS_DLGINSPPARAMS_DETECTMODELPARAMS_MINSCORE 298
#define IDS_DLGINSPPARAMS_DETECTMODELPARAMS_ACCURACY 299
#define IDS_DLGINSPPARAMS_DETECTMODELPARAMS_GREEDINESS 300
#define IDS_DLGINSPPARAMS_DETECTMODELPARAMS_PYRAMIDLEVELS 301
#define IDS_DLGINSPPARAMS_DETECTMODELPARAMS_MAXOVERLAP 302
#define IDS_DLGINSPPARAMS_MEASPARAMS    303
#define IDS_DLGINSPPARAMS_MEASPARAMSLINE 304
#define IDS_DLGINSPPARAMS_MEASPARAMSCIRCLE 305
#define IDS_DLGINSPPARAMS_MEASPARAMSRECT 306
#define IDS_DLGINSPPARAMS_MEASPARAMSELLIPSE 307
#define IDS_DLGINSPPARAMS_MEASPARAMS_LENGTH1 308
#define IDS_DLGINSPPARAMS_MEASPARAMS_LENGTH2 309
#define IDS_DLGINSPPARAMS_MEASPARAMS_SIGMA 310
#define IDS_DLGINSPPARAMS_MEASPARAMS_MINSCORE 311
#define IDS_DLGINSPPARAMS_MEASPARAMS_EDGETHRESH 312
#define IDS_DLGINSPPARAMS_MEASPARAMS_DISTTHRESH 313
#define IDS_DLGINSPPARAMS_ALGOPARAMS_MAXCLOSUREDIST 314
#define IDS_VERTICES                    315
#define IDS_DLGTRACKERMARGIN            316
#define IDS_MEASRECTTOARC               317
#define IDS_MEASRECTTORECT              318
#define IDS_MN_SETTINGS_TRACKER         319
#define IDS_MEASRECTTOCIRCLE            320
#define IDS_ELLIPSE_FAIL                321
#define IDS_DLG_MEAS_MAJOR_RAD_ELLIPSE  322
#define IDS_DLG_MEAS_MINOR_RAD_ELLIPSE  323
#define IDS_DLG_MEAS_ROTATION_ANGLE_ELLIPSE 324
#define IDS_MEASLINETOELLIPSE           325
#define IDS_MEASCIRCLETOELLIPSE         326
#define IDS_MEASARCTOELLIPSE            327
#define IDS_MEASPOINTTOELLIPSE          328
#define IDS_MEASRECTTOELLIPSE           329
#define IDS_MEASELLIPSETOELLIPSE        330
#define IDS_MODEL_ANGLE_START           331
#define IDS_MODEL_ANGLE_END             332
#define IDS_MODEL_ANGLE_STEP            333
#define IDS_DLGINSPPARAMS_LARGEMODELPARAMS 334
#define IDS_DLGINSPPARAMS_DETECTLARGEMODELPARAMS 335
#define IDS_MEASSLOT                    336
#define IDS_MEASCIRCLETOSLOT            337
#define IDS_MEASARCTOSLOT               338
#define IDS_MEASRECTTOSLOT              339
#define IDS_MEASELLIPSETOSLOT           340
#define IDS_MEASPOLY                    341
#define IDS_MEASCIRCLETOPOLY            342
#define IDS_MEASARCTOPOLY               343
#define IDS_MEASRECTTOPOLY              344
#define IDS_MEASELLIPSETOPOLY           345
#define IDS_MEASSLOTTOPOLY              346
#define IDS_DLGLINESELECT_THROUGH_CIRCLE_LINES 347
#define IDS_DLGLINESELECT_THROUGH_TANGENT_LINES 348
#define IDS_DLGLINESELECT_PERPRNDICULAR_BISECTOR 349
#define IDS_DLGCONTINSP_ST_TIME_BTW_2SETS 350
#define IDS_DLGCONTINSP_ST_NUMBER_OF_JOB_SETS 351
#define IDS_DLGCONTINSP_CHK_AUTO_CREATE_EXCEL 352
#define IDS_DLGCONTINSP_CHK_SHOW_XLS    353
#define IDS_DLGCONTINSP_ST_EXCEL_PATH   354
#define IDS_DLGCONTINSP_BTN_NEW_EXCEL_FILE 355
#define IDS_DLGCONTINSP_BTN_BROWSE_EXCEL_FILE 356
#define IDS_DLGCONTINSP_BTN_OPEN_EXCEL_FILE 357
#define IDS_DLGCONTINSP_RAD_CUSTOM_FORMAT 358
#define IDS_DLGCONTINSP_RAD_DEF_FORMAT1 359
#define IDS_DLGCONTINSP_RAD_DEF_FORMAT2 360
#define IDS_DLGCONTINSP_BTN_HEADER_SETTING 361
#define IDS_DLGCONTINSP_RAD_SELECTED_DATA 362
#define IDS_DLGCONTINSP_RAD_DATA_WITH_TOLERANCE 363
#define IDS_DLGCONTINSP_CHK_PAUSE_OVERSTEP_TOLEARNCES 364
#define IDS_DLGCONTINSP_CHK_SINGLE_STEP_MODE 365
#define IDS_DLGCONTINSP_CHK_POSITIONING_NOT_MEASURED 366
#define IDS_DLGCONTINSP_CHK_AUTO_RUN_NEXT_STEP 367
#define IDS_DLGCONTINSP_CHK_AUTO_SAVE_SETTING 368
#define IDS_DLGCONTINSP_CHK_SET_DEFAULT 369
#define IDS_DLGCONTINSP_CHK_EXPORT_NAME 370
#define IDS_DLGCONTINSP_CHK_EXPORT_STD_VALUE 371
#define IDS_DLGCONTINSP_CHK_EXPORT_UPPER_TOL 372
#define IDS_DLGCONTINSP_CHK_EXPORT_LOWER_TOL 373
#define IDS_DLGCONTINSP_CHK_EXPORT_VALUE 374
#define IDS_DLGCONTINSP_CHK_EXPORT_ERROR 375
#define IDS_DLGCONTINSP_CHK_EXPORT_JUDGED 376
#define IDS_DLGCONTINSP_CHK_EXPORT_MEAS_TIME 377
#define IDS_DLGCONTINSP_CHK_EXPORT_OVERFLOW_STATE 378
#define IDS_CONSTRUCTLINEL2C_VERTICAL_LINE_L2C 379
#define IDS_CONSTRUCTLINEL2C_IIeI_LINE_TANGENT_CIRCLE 380
#define IDS_CONSTRUCTLINEP2P_CONSTUCT_LINE_THROUGH_POINTS 381
#define IDS_CONSTRUCTLINEP2C_CONSTRUCT_LINE_TANGENTS_P2C 382
#define IDS_CONTROLPANE_ST_CLICKED_SHAPES 383
#define IDS_CONTROLPANE_CV_GB_AUTOFINDSHAPES 384
#define IDS_CONTROLPANE_ST_LABELS       385
#define IDS_CONTROLPANE_ST_CONSTRUCT_LINE_POINT 386
#define IDS_CONTROLPANE_ST_MEASUREMENT_CONTROL_PANE 387
#define IDS_CONTROLPANE_ST_LINE_ADJUSTMENTS 388
#define IDS_CONTROLPANE_ST_COORDINATE_AXES 389
#define IDS_CONTROLPANE_ST_OTHERS       390
#define IDS_REPORT_SELECT               391
#define IDS_REPORT_CANCEL_SELECT        392
#define IDS_REPORT_SELECT_ALL           393
#define IDS_REPORT_SELECT_NONE          394
#define IDS_TOLERANCE_BATCH_SET         395
#define IDS_TOLERANCE_BATCH_DELETE      396
#define IDS_MEASELLIPSE                 397
#define IDS_MEAS_PROPORTION             398
#define IDS_MEAS_MINOR_LENGTH           399
#define IDS_MEAS_MAJOR_LENGTH           400
#define IDS_MEAS_RAD_MAJOR              401
#define IDS_MEAS_RAD_MINOR              402
#define IDS_MEAS_ROTATION_ANGLE         403
#define IDS_MEAS_ELLIPSE_SHAPEWARP      404
#define IDS_REPORT_BATCH_SELECT         405
#define IDS_REPORT_BATCH_CANCEL_SELECT  406
#define IDS_TOLERANCE_EDIT              407
#define IDS_TOLERANCE_DELETE            408
#define IDS_REPORT_DESELECT             409
#define IDS_MEAS_AVG_CNTR_DIST          410
#define IDS_MEAS_XYLINEAR               411
#define IDS_MEAS_RADIUS                 412
#define IDS_MEAS_DIAMETER               413
#define IDS_MEAS_XYCOORD                414
#define IDS_MEAS_ANGLE                  415
#define IDS_SEL_CLKD_LINE               416
#define IDS_SEL_CLKD_CIRCLE             417
#define IDS_SEL_CLKD_ARC                418
#define IDS_SEL_CLKD_RECT               419
#define IDS_SEL_CLKD_SLOT               420
#define IDS_SEL_LINE_MERGE              421
#define IDS_EDGE_DETECTION_PARAMS       422
#define IDS_RAD_DLGEXCEL_SELECTED_DATA_PRE_ARRANGED_FORMAT 423
#define IDS_RAD_DLGEXCEL_SELECTED_DATA_USER_DEFINED_FORMAT 424
#define IDS_RAD_DLGEXCEL_DATA_WITH_TOL_USER_DEFINED_FORMAT 425
#define IDS_RAD_DLGEXCEL_TEMPLETE_CREATE_NEW 426
#define IDS_RAD_DLGEXCEL_ADD_TO_EXISTENT_FILE 427
#define IDS_CHK_DLGEXCEL_COPY_DURING_RUNNING 428
#define IDS_RAD_DLGEXCEL_OUTPUT_LEFT_TO_RIGHT 429
#define IDS_RAD_DLGEXCEL_OUTPUT_TOP_TO_BOTTOM 430
#define IDS_RAD_DLGEXCEL_VALUE_MODE     431
#define IDS_RAD_DLGEXCEL_TEXT_MODE      432
#define IDS_STATIC_DLGEXCEL_GOOD        433
#define IDS_STATIC_DLGEXCEL_NO_GOOD     434
#define IDS_CHK_DLGEXCEL_EXPORT_STD_VALUE_WITH_TOL 435
#define IDS_DLG_EXPORT_EXCEL            436
#define IDS_RADIO_TOL_SAME_TYPE         437
#define IDS_RADIO_TOL_SEL_SAME_TYPE     438
#define IDS_STATIC_STD_VAL              439
#define IDS_STATIC_UPPER_TOLERANCE      440
#define IDS_STATIC_LOWER_TOLERANCE      441
#define IDS_RADIO_STDVAL_MEAS_VAL       442
#define IDS_RADIO_STDVALUE_SETVALUE     443
#define IDS_TOTAL_SAMPLES_MEASURED      444
#define IDS_PRIMITIVE_NAME              445
#define IDS_AVERAGE                     446
#define IDS_VARIANCE                    447
#define IDS_CA                          448
#define IDS_CP                          449
#define IDS_CPK                         450
#define IDS_ARTIFACT_NO                 451
#define IDS_SUBSIDIARY_BARCODE          452
#define IDS_MEASURING_TIME              453
#define IDS_MEASURED_DATA               454
#define IDS_WORKPIECE                   455
#define IDS_NAME                        456
#define IDS_SPECIFICATIONS              457
#define IDS_MEASURE                     458
#define IDS_ERROR                       459
#define IDS_JUDGED                      460
#define IDS_OVERSTEP                    461
#define IDS_OBJECT_NO                   462
#define IDS_ITEM_NAME                   463
#define IDS_STANDARD                    464
#define IDS_UP_TOL                      465
#define IDS_DOWN_TOL                    466
#define IDS_MAX                         467
#define IDS_MIN                         468
#define IDS_SAMPLE                      469
#define IDS_SAMPLE_NUMBER               470
#define IDS_GROUP                       471
#define IDS_AVG                         472
#define IDS_RANGE                       473
#define IDS_MEDIAN                      474
#define IDS_STD_DEV                     475
#define IDS_DATE                        476
#define IDS_TOTAL_SAMPLES               477
#define IDS_FAILURE                     478
#define IDS_DATE_TIME                   479
#define IDS_VALID_POINTS_MSG            480
#define IDS_BAR_CHART                   481
#define IDS_MEAS_VALUES                 482
#define IDS_PARAMATER                   483
#define IDS_VALUE                       484
#define IDS_UP_LIMIT                    485
#define IDS_DOWN_LIMIT                  486
#define IDS_OVERSTEP_NUMBER             487
#define IDS_OVERSTEP_UPPER_LIMIT        488
#define IDS_OVERSTEP_LOWER_LIMIT        489
#define IDS_MN_FILE                     490
#define IDS_MN_EDIT                     491
#define IDS_MN_VIEW                     492
#define IDS_BIN_POPULATION              492
#define IDS_MN_IMAGE                    493
#define IDS_MN_GEOMETRY                 494
#define IDS_MN_TOLERANCE                495
#define IDS_MN_LABEL                    496
#define IDS_MN_COORDINATES              497
#define IDS_MN_INSPECTION               498
#define IDS_MN_WINDOW                   499
#define IDS_MN_SETTINGS                 500
#define IDS_MN_LANGUAGE                 501
#define IDS_MN_HELP                     502
#define IDS_MN_NEW                      503
#define IDS_MN_FILE_NEW                 503
#define IDS_MN_OPEN                     504
#define IDS_MN_FILE_OPEN                504
#define IDS_MN_SAVE                     505
#define IDS_MN_FILE_SAVE                505
#define IDS_MN_SAVEAS                   506
#define IDS_MN_FILE_SAVEAS              506
#define IDS_MN_LOADDXFFILE              507
#define IDS_MN_FILE_LOADDXFFILE         507
#define IDS_DLG_MEAS_L2LDIST            508
#define IDS_MN_LOAD_DXF_OPTIONS         509
#define IDS_MN_LOAD_FILE_DXF_OPTIONS    509
#define IDS_MN_MATCH_DXF_COORDINATES    510
#define IDS_MN_FILE_MATCH_DXF_COORDINATES 510
#define IDS_DLG_MEAS_LINEAR_DIST        511
#define IDS_MN_FILE_REPORT              512
#define IDS_MN_FILE_EXIT                513
#define IDS_MN_FILE_REPORT_MS_WORD      514
#define IDS_MN_FILE_REPORT_MS_EXCEL     515
#define IDS_MN_EXPORT_PDF               516
#define IDS_MN_FILE_REPORT_PDF          516
#define IDS_MN_UNDO                     517
#define IDS_MN_EDIT_UNDO                517
#define IDS_MN_CUT                      518
#define IDS_MN_EDIT_CUT                 518
#define IDS_MN_COPY                     519
#define IDS_MN_EDIT_COPY                519
#define IDS_MN_PASTE                    520
#define IDS_MN_EDIT_PASTE               520
#define IDS_MN_FILE_RECENT_FILE         521
#define IDS_FIT_VIEW                    522
#define IDS_DLG_MEAS_ANGLE_BET_LINES    522
#define IDS_MN_DELETE_SELECTED          523
#define IDS_MN_EDIT_DELETE_SELECTED     523
#define IDS_MN_CUT_LINE                 524
#define IDS_MN_EDIT_CUT_LINE            524
#define IDS_MN_EXTEND_LINE              525
#define IDS_MN_EDIT_EXTEND_LINE         525
#define IDS_MN_DRAW_PARALLEL_LINE       526
#define IDS_MN_EDIT_DRAW_PARALLEL_LINE  526
#define IDS_MN_DRAW_VERTICAL_LINE       527
#define IDS_MN_EDIT_DRAW_VERTICAL_LINE  527
#define IDS_MN_DRAW_CONCENTRIC_CIRCLE   528
#define IDS_MN_EDIT_DRAW_CONCENTRIC_CIRCLE 528
#define IDS_MN_TOOLBAR                  529
#define IDS_MN_EDIT_DRAW_HORIZ_LINE     529
#define IDS_MN_STATUS_BAR               530
#define IDS_DLG_CALIB_3POINT            530
#define IDS_MN_REFRESH                  531
#define IDS_DLG_CALIB_CALCULATE         531
#define IDS_MN_SHOW_GRID                532
#define IDS_MN_IMAGE_CAPTURE_IMAGE      532
#define IDS_MN_CAMERA_SETTINGS          533
#define IDS_MN_IMAGE_LIVE_STREAM        533
#define IDS_MN_CAPTURE_IMAGE            534
#define IDS_MN_IMAGE_FREEZE_STREAM      534
#define IDS_MN_FREEZE_STREAM            535
#define IDS_MN_IMAGE_ZOOM_IN            535
#define IDS_MN_ZOOM_IN                  536
#define IDS_MN_IMAGE_ZOOM_OUT           536
#define IDS_MN_ZOOM_OUT                 537
#define IDS_MN_IMAGE_ZOOM_TO_FIT        537
#define IDS_MN_ZOOM_TO_FIT              538
#define IDS_MN_IMAGE_IMAGE_LOAD         538
#define IDS_MN_SAVE_IMAGE               539
#define IDS_MN_IMAGE_SAVE_IMAGE         539
#define IDS_MN_POINT                    540
#define IDS_MN_GEOMETRY_POINT           540
#define IDS_MN_LINE                     541
#define IDS_MN_GEOMETRY_LINE            541
#define IDS_MN_ARC                      542
#define IDS_MN_GEOMETRY_ARC             542
#define IDS_MN_CIRCLE                   543
#define IDS_MN_GEOMETRY_CIRCLE          543
#define IDS_MN_ELLIPSE                  544
#define IDS_MN_GEOMETRY_ELLIPSE         544
#define IDS_MN_SLOT                     545
#define IDS_MN_GEOMETRY_SLOT            545
#define IDS_MN_RECTANGLE                546
#define IDS_MN_GEOMETRY_RECTANGLE       546
#define IDS_MN_POLYGON                  547
#define IDS_MN_GEOMETRY_POLYGON         547
#define IDS_MN_SPLINE                   548
#define IDS_MN_GEOMETRY_SPLINE          548
#define IDS_MN_PARALLELISM              549
#define IDS_MN_TOLERANCE_PARALLELISM    549
#define IDS_MN_VERTICALITY              550
#define IDS_MN_TOLERANCE_VERTICALITY    550
#define IDS_MN_ANGULARITY               551
#define IDS_MN_TOLERANCE_ANGULARITY     551
#define IDS_MN_POSITION                 552
#define IDS_MN_TOLERANCE_POSITION       552
#define IDS_MN_CONCENTRICITY            553
#define IDS_MN_TOLERANCE_CONCENTRICITY  553
#define IDS_MN_SYMMETRY                 554
#define IDS_MN_TOLERANCE_SYMMETRY       554
#define IDS_MN_PROFILE                  555
#define IDS_MN_TOLERANCE_PROFILE        555
#define IDS_MN_HORIZONTAL_LABEL         556
#define IDS_MN_LABEL_HORIZONTAL         556
#define IDS_MN_VERTICAL_LABEL           557
#define IDS_MN_LABEL_VERTICAL           557
#define IDS_MN_LINEAR_LABEL             558
#define IDS_MN_LABEL_LINEAR             558
#define IDS_MN_BASELINE_LABEL           559
#define IDS_MN_LABEL_BASELINE           559
#define IDS_MN_RADIUS_LABEL             560
#define IDS_MN_LABEL_RADIUS             560
#define IDS_MN_DIAMETER_LABEL           561
#define IDS_MN_LABEL_DIAMETER           561
#define IDS_MN_XY_COORD_LABEL           562
#define IDS_MN_LABEL_XY_COORD           562
#define IDS_MN_TEXT_LABEL               563
#define IDS_MN_LABEL_TEXT               563
#define IDS_MN_EDIT_LABEL               564
#define IDS_MN_LABEL_EDIT               564
#define IDS_MN_TRANSLATE_ORIGIN         565
#define IDS_MN_COORD_TRANSLATE_ORIGIN   565
#define IDS_MN_FORM_X_AXIS              566
#define IDS_MN_COORD_FORM_X_AXIS        566
#define IDS_MN_FORM_Y_AXIS              567
#define IDS_MN_COORD_FORM_Y_AXIS        567
#define IDS_MN_TRANSLATE_AND_ROTATE_AXES 568
#define IDS_MN_COORD_TRANSLATE_AND_ROTATE_AXES 568
#define IDS_MN_TEST_IMAGE               569
#define IDS_MN_INSP_TEST_IMAGE          569
#define IDS_MN_ONLINE_INSPECTION        570
#define IDS_DLG_MEAS_L2CDIST            570
#define IDS_MN_EDIT_TEMPLATE            571
#define IDS_MN_INSP_EDIT_TEMPLATE       571
#define IDS_MN_LOAD_MODEL               572
#define IDS_MN_INSP_LOAD_MODEL          572
#define IDS_MN_MOTION_MANAGER           573
#define IDS_MN_SETTINGS_MOTION_MANAGER  573
#define IDS_MN_JOB_CONFIGURATION        574
#define IDS_MN_SETTINGS_JOB_CONFIGURATION 574
#define IDS_MN_JOB_MANAGEMENT           575
#define IDS_MN_SETTINGS_JOB_MANAGEMENT  575
#define IDS_MN_CAMERA_TYPE              576
#define IDS_MN_SETTINGS_CAMERA_TYPE     576
#define IDS_MN_JOB_GRID                 577
#define IDS_MN_SETTINGS_JOB_GRID        577
#define IDS_MN_LIGHT_CONTROLS           578
#define IDS_MN_SETTINGS_LIGHT_CONTROLS  578
#define IDS_MN_INSPECTION_PARAMETERS    579
#define IDS_MN_SETTINGS_INSPECTION_PARAMETERS 579
#define IDS_MN_CALIBRATION              580
#define IDS_MN_SETTINGS_CALIBRATION     580
#define IDS_MN_CHINESE                  581
#define IDS_MN_LANG_CHINESE             581
#define IDS_MN_ABOUT                    582
#define IDS_MN_FILE_REPORT_TEXT_FILE    583
#define IDS_MN_FILE_REPORT_MS_ACCESS    584
#define IDS_MN_FILE_REPORT_DXF          585
#define IDS_MN_FILE_REPORT_IGES         586
#define IDS_MN_SETTINGS_CALIB_CAMERA    587
#define IDS_MN_SETTINGS_CALIB_NLC       588
#define IDS_MN_SETTINGS_CALIB_AUTOXY    589
#define IDS_MN_SETTINGS_CALIB_THREEPOINT 590
#define IDS_MN_SETTINGS_CALIB_FFC       591
#define IDS_MN_WINDOW_CAD               592
#define IDS_MN_WINDOW_VIDEO             593
#define IDS_MN_SETTINGS_CAMERA          594
#define IDS_MN_SETTINGS_MOTION          595
#define IDS_MN_SETTINGS_JOB             596
#define IDS_MN_LANG_ENGLISH             597
#define IDS_MN_HELP_ABOUT               598
#define IDS_HIGH                        599
#define IDS_LOW                         600
#define IDS_OK                          601
#define IDS_CANCEL                      602
#define IDS_SELECT                      603
#define IDS_DELETE                      604
#define IDS_START                       605
#define IDS_STOP                        606
#define IDS_BACK                        607
#define IDS_CLOSE                       608
#define IDS_DLG_EDP                     609
#define IDS_DLG_EDP_MANUAL_OVERRIDE     610
#define IDS_DLG_EDP_FORCE_LINE_ORIENTATION 611
#define IDS_DLG_MEASUREMENTS            612
#define IDS_DLG_MEAS_NOMINAL            613
#define IDS_DLG_MEAS_TOL_UP             614
#define IDS_DLG_MEAS_TOL_LOW            615
#define IDS_DLG_MEAS_XDIST              616
#define IDS_DLG_MEAS_YDIST              617
#define IDS_DLG_MEAS_CNTRDIST           618
#define IDS_DLG_MEAS_A2ADIST            619
#define IDS_DLG_MEAS_C2CDIST            620
#define IDS_DLG_MEAS_C2ADIST            621
#define IDS_DLG_MEAS_L2ADIST            622
#define IDS_DLG_MEAS_NEARDIST           623
#define IDS_DLG_MEAS_FARDIST            624
#define IDS_DLG_MEAS_CENTER             625
#define IDS_DLG_MEAS_RAD                626
#define IDS_DLG_MEAS_DIA                627
#define IDS_DLG_MEAS_PROF_ERR           628
#define IDS_DLG_MEAS_MIN_RAD            629
#define IDS_DLG_MEAS_MAX_RAD            630
#define IDS_DLG_MEAS_ROUNDNESS          631
#define IDS_DLG_MEAS_PERIMETER          632
#define IDS_DLG_MEAS_AREA               633
#define IDS_DLG_MEAS_LINE               634
#define IDS_DLG_MEAS_CIRCLE             635
#define IDS_DLG_JOB_ENTERNAME           636
#define IDS_DLG_JOB_ADD                 637
#define IDS_DLG_JOB_DELETE              638
#define IDS_DLG_JOB_CHANGE              639
#define IDS_DLG_JOB_SELECT              640
#define IDS_DLG_JOB_ADD_NEW             641
#define IDS_DLG_JOBGRID                 642
#define IDS_DLG_JOBGRID_FIXED           643
#define IDS_DLG_JOBGRID_RANDOM          644
#define IDS_DLG_JOBGRID_NO_OF_JOBS      645
#define IDS_DLG_JOBGRID_NO_OF_ROWS      646
#define IDS_DLG_JOBGRID_NO_OF_COLS      647
#define IDS_DLG_JOBGRID_X_PITCH         648
#define IDS_DLG_JOBGRID_Y_PITCH         649
#define IDS_DLG_JOBGRID_LAYOUT          650
#define IDS_DLG_CAM_EXP                 651
#define IDS_DLG_CAM_EXP_TIME            652
#define IDS_DLG_CAM_ACQ_LINE_RATE       653
#define IDS_DLG_CAM_SENSOR_SCAN_DIR     654
#define IDS_DLG_CAM_MAN_DIR_CHNG        655
#define IDS_DLG_CAM_FORWARD             656
#define IDS_DLG_CAM_REVERSE             657
#define IDS_DLG_CAM_TDI_ROWS            658
#define IDS_DLG_CAM_AOI_OFFSET          659
#define IDS_DLG_CAM_AOI_WIDTH           660
#define IDS_DLG_CAM_COMP_COND           661
#define IDS_DLG_CAM_PARAM_SETT          662
#define IDS_DLG_CAM_DARK_CORR           663
#define IDS_DLG_CAM_WHITE_CORR          664
#define IDS_DLG_CAM_GAMMA_CORR          665
#define IDS_DLG_LED_CONTROL             666
#define IDS_DLG_LED_DUTY_CYCLE          667
#define IDS_DLG_JOB_LENGTH              668
#define IDS_DLG_JOB_WIDTH               669
#define IDS_DLG_XAXIS_START_LOC         670
#define IDS_DLG_YAXIS_START_LOC         671
#define IDS_DLG_ZAXIS_START_LOC         672
#define IDS_DLG_GRAB_AXIS               673
#define IDS_DLG_MOVE_SPEED              674
#define IDS_DLG_HOME_SPEED              675
#define IDS_DLG_JOG_SPEED               676
#define IDS_DLG_JOYSTICK_SPEED          677
#define IDS_DLG_XAXIS                   678
#define IDS_DLG_YAXIS                   679
#define IDS_DLG_ZAXIS                   680
#define IDS_DLG_UAXIS                   681
#define IDS_DLG_HOME                    682
#define IDS_DLG_JOB_LOC                 683
#define IDS_DLG_SET_LABEL               684
#define IDS_DLG_USER                    685
#define IDS_DLG_USER_LOGIN              686
#define IDS_DLG_USER_LEVEL              687
#define IDS_DLG_USER_NAME               688
#define IDS_DLG_USER_PASSWORD           689
#define IDS_DLG_USER_ADD                690
#define IDS_DLG_CALIB_MASTER_PARAMS     691
#define IDS_DLG_CALIB_CHESS_BOARD       692
#define IDS_DLG_CALIB_SYM_CIRCLES       693
#define IDS_DLG_CALIB_ASSYM_CIRCLES     694
#define IDS_DLG_CALIB_ROWS_OF_SQ_CIR    695
#define IDS_DLG_CALIB_COLS_OF_SQ_CIR    696
#define IDS_DLG_CALIB_SQ_CIR_SIZE       697
#define IDS_DLG_CALIB_DIST_SQ_CIR       698
#define IDS_DLG_CALIB_MASTER_CIR_DIA    699
#define IDS_DLG_CALIB_DIST_2_CIR        700
#define IDS_DLG_CALIB_ENABLE_COMP       701
#define IDS_DLG_CALIB_LOAD_COMP         702
#define IDS_DLG_CALIB_SAVE_COMP         703
#define IDS_DLG_CALIB_ENABLE_CORR       704
#define IDS_DLG_CALIB_HW_CORR           705
#define IDS_DLG_CALIB_PIXEL_REPLACE     706
#define IDS_DLG_CALIB_LOAD              707
#define IDS_DLG_CALIB_CORR_TYPE         708
#define IDS_DLG_CALIB_VIDEO_TYPE        709
#define IDS_DLG_CALIB_MAX_BLCK          710
#define IDS_DLG_CALIB_AVG_LINES         711
#define IDS_DLG_CALIB_AVG_FRAMES        712
#define IDS_DLG_CALIB_VER_OFFSET        713
#define IDS_DLG_CALIB_DEV_DARK_PXL      714
#define IDS_DLG_CALIB_DEV_BRIGHT_PXL    715
#define IDS_DLG_CALIB_NO_CLUSTER_MAP    716
#define IDS_DLG_CALIB_LOAD_CLUSTER_MAP  717
#define IDS_DLG_CALIB_INDEX             718
#define IDS_DLG_CALIB_CONSIDER          719
#define IDS_DLG_CALIB_STEP1             720
#define IDS_DLG_CALIB_STEP2             721
#define IDS_DLG_CALIB_STEP3             722
#define IDS_DLG_CALIB_ACQ_DARK_IMG      723
#define IDS_DLG_CALIB_ACQ_BRIGHT_IMG    724
#define IDS_DLG_CALIB_SAVE_UPLOAD       725
#define IDS_DLG_CALIB_USER_FFC_DEST     726
#define IDS_DLG_ABOUT_VER               727
#define IDS_DLG_ABOUT_COPYRIGHT         728
#define IDS_DLG_CAMERA_FEATURES         729
#define IDS_SAVE                        730
#define IDS_DLG_NLC_AUTO_DETECT_CIR     731
#define IDS_DLG_JOB                     732
#define IDS_DLG_PARAMETERS              733
#define IDS_DLG_TOL_SEL_MEAS            734
#define IDS_DLG_TOL_POS                 735
#define IDS_DLG_TOL_MIN_DIST            736
#define IDS_DLG_TOL_MAX_DIST            737
#define IDS_DLG_TOL_INCL_ANG_MIN        738
#define IDS_DLG_TOL_INCL_ANG_MAX        739
#define IDS_UPDATE                      740
#define IDS_DLG_LINE_SPT_X              741
#define IDS_DLG_LINE_SPT_Y              742
#define IDS_DLG_LINE_EPT_X              743
#define IDS_DLG_LINE_EPT_Y              744
#define IDS_DLG_LINE_MPT_X              745
#define IDS_DLG_LINE_MPT_Y              746
#define IDS_DLG_LINE_ANG                747
#define IDS_DLG_LINE_LENGTH             748
#define IDS_DLG_CALIB_3POINT_SIZE       749
#define IDS_DLG_CALIB_3POINT_NO_OF_PIXELS 750
#define IDS_DLG_CALIB_3POINT_XCALIB     751
#define IDS_DLG_CALIB_3POINT_YCALIB     752
#define IDS_DLG_CALIB_3POINT_C1_C2      753
#define IDS_DLG_CALIB_3POINT_C1_C3      754
#define IDS_DLG_COORD_ANGLE             755
#define IDS_DEGREES                     756
#define IDS_MN_IMAGE_ZOOM100            757
#define IDS_MEAS_ADD                    758
#define IDS_CANCEL_CURRENT_OPER         759
#define IDS_REFRESH_ALL_VIEWS           760
#define IDS_MN_INSP_CONT_INSP           761
#define IDS_MN_INSP_EDIT_AUTO           762
#define IDS_MN_INSP_EDIT_MANUAL         763
#define IDS_DELETE_SHAPE                764
#define IDS_WINDOW_VIDEO                765
#define IDS_WINDOW_CAD                  766
#define IDS_DELETE_ALL                  767
#define IDS_SET_COORDINATE              768
#define IDS_MENU_INSP_START             769
#define IDS_MENU_INSP_PAUSE             770
#define IDS_MENU_INSP_STOP              771
#define IDS_MN_SETTINGS_CALIB_LENS_CORRECTION 772
#define IDS_MN_SETTINGS_CALIB_LENS_PAN_ENTITY_SETTINGS 773
#define IDS_MN_SETTINGS_CALIB_LENS_DETECT_COMPENSATION_POINTS 774
#define IDS_MN_SETTINGS_CALIB_LENS_ENABLE_LENS_CORRECTION 775
#define IDS_PROCESS_CAPABILITY_ANALYSIS 776
#define IDS_POPULATION                  777
#define IDS_LSL                         778
#define IDS_USL                         779
#define IDS_SAMPLE_MEAN                 780
#define IDS_WITHIN_SIGMA                781
#define IDS_OVERALL_SIGMA               782
#define IDS_CPL                         783
#define IDS_CPU                         784
#define IDS_PP                          785
#define IDS_PPK                         786
#define IDS_PPL                         787
#define IDS_PPU                         788
#define IDS_CALIB_CHECKBOARD_CHCK       789
#define IDS_JOB_DETECTION_FAIL          790
#define IDS_TMPLT_CREATION_FAIL         791
#define IDS_TMPLT_CREATION_SUCCESS      792
#define IDS_CFG_FILE_CREATE_FAILS       793
#define IDS_MEASSPLINE                  794
#define IDS_MEASLINETOSPLINE            795
#define IDS_MEASCIRCLETOSPLINE          796
#define IDS_MEASARCTOSPLINE             797
#define IDS_MEASRECTTOSPLINE            798
#define IDS_MEASELLIPSETOSPLINE         799
#define IDS_MEASSLOTTOSPLINE            800
#define IDS_MEASPOLYTOSPLINE            801
#define IDS_MEASSPLINETOSPLINE          802
#define IDS_MEASPOINTTOSPLINE           803
#define IDS_POINTSCOUNT                 804
#define IDS_COORD_XAXIS                 805
#define IDS_COORD_YAXIS                 806
#define IDS_COORD_TRANS                 807
#define IDS_COORD_TRANS_ROTATE          808
#define IDS_DELETEALLCONFIRMMSG         809
#define IDS_DELETEPRGSTEPWARNING        810
#define IDS_GRIDMEASRESULTTITLECOL1     811
#define IDS_CHCK_PAN_ENTITY_INTERVAL    812
#define IDS_JOB_THICKNESS               813
#define IDS_EXIT_DETECT_COMP_POINTS     814
#define IDS_START_GRAB_LOC              815
#define IDS_CAMEXPERT_RUNNING           816
#define IDS_SAPERAMONITOR_RUNNING       817
#define IDS_EDGEDETECTZOOMWARNING       818
#define IDS_LENSCORR_COMPUTEFIXEDGRIDPOINTS 819
#define IDS_LENSCORR_COMPUTE_FIXED_PNTS_SUCCESS 820
#define IDS_LENSCORR_COMPUTE_FIXED_PNTS_FAILED 821
#define IDS_NGCOLORSET                  822
#define IDS_DLG_JOB_SAVE_AS             823
#define IDS_DISABLE_MAP                 824
#define IDS_ERMSG_MAPNOTLOADED          825
#define IDS_ENPREVJOBLOAD               826
#define IDS_DISABLEPREVJOBLOAD          827
#define IDS_AUTO_FIND_SEC               828
#define IDS_DXF_PARAMS                  829
#define IDS_NO_DATA_AVAILABLE           837
#define IDS_NO_SUFF_DATA_AVAILABLE      838
#define IDS_INVALID_VALUES_NO_GRAPH     839
#define IDS_DEPT                        840
#define IDS_MACHINE_NO                  841
#define IDS_FREQUENCY                   842
#define IDS_SERIAL_NO                   843
#define IDS_MACHINE                     844
#define IDS_TABLE                       845
#define IDS_VALUES                      846
#define IDS_CHART                       847
#define IDS_GRID                        848
#define IDS_SIGMA                       849
#define IDS_ANALYSIS                    850
#define IDS_FAILED_DATA_POINTS          851
#define IDS_EXCEL_APP_ERROR             852
#define IDS_SIMPLE_ANALYSIS_CHART       853
#define IDS_PROCESS_CAPABILITY_CHART    854
#define IDS_GOOD_JOB                    855
#define IDS_BAD_JOB                     856
#define IDS_TYPE                        857
#define IDS_POSITIONING                 858
#define IDS_CALCULATION                 859
#define IDS_CORRELATIVE_OBJECTS         860
#define IDS_PROGRAM_LIST                861
#define IDS_MSG_CORRECT_START_CELL      862
#define IDS_MSG_SEL_EXCEL_FILE          863
#define IDS_MSG_FILE_NOT_FOUND          864
#define IDS_MSG_FILE_DELETE_IN_OPEARTION 865
#define IDS_MSG_INSERT_JOB_NAME         866
#define IDS_MEG_JOB_NAME_EXIST          867
#define IDS_DXF_OPTION_STATIC_TEXT      868
#define IDS_DXF_OPTION_CIRCLE           869
#define IDS_DXF_OPTION_LABEL            870
#define IDS_DXF_OPTION_OTHER_OBJECTS    871
#define IDS_DXF_MEAS_ELEMENT1           872
#define IDS_DXF_MEAS_ELEMENT2           873
#define IDS_DXF_DXF_ELEMENT1            874
#define IDS_DXF_DXF_ELEMENT2            875
#define IDS_MSG_NO_INTERSECTIONS        881
#define IDS_MN_LABEL_ANGLE              882
#define IDS_DLGCOLORSET_STATIC_LINE_COLOR 883
#define IDS_DLGCOLORSET_STATIC_ARC_COLOR 884
#define IDS_DLGCOLORSET_STATIC_ELLIPSE_COLOR 885
#define IDS_DLGCOLORSET_STATIC_RECT_COLOR 886
#define IDS_DLGCOLORSET_STATIC_SPLINE_COLOR 887
#define IDS_DLGCOLORSET_STATIC_SLOT_COLOR 888
#define IDS_DLGCOLORSET_STATIC_LABEL_COLOR 889
#define IDS_DLGCOLORSET_STATIC_TEXT_LABEL_COLOR 890
#define IDS_DLGCOLORSET_STATIC_SELECT_FEAT_COLOR 891
#define IDS_DLGCOLORSET_STATIC_EDGE_POINT_COLOR 892
#define IDS_DLGCOLORSET_STATIC_TEMP_FEAT_COLOR 893
#define IDS_DLGCOLORSET_STATIC_COORD_AXIS_COLOR 894
#define IDS_DLGCOLORSET_STATIC_FEAT_POINT_RECT_COLOR 895
#define IDS_DLGCOLORSET_STATIC_FEAT_LABEL_COLOR 896
#define IDS_DLGCOLORSET_STATIC_FEAT_LABEL_HIGHTLIGHT_COLOR 897
#define IDS_DLGCOLORSET_STATIC_COORDI_LABEL_COLOR 898
#define IDS_DLGCOLORSET_STATIC_COORDI_LABEL_HIGHLIGHT_COLOR 899
#define IDS_DLGCOLORSET_STATIC_POLY_COLOR 900
#define IDS_DLGCOLORSET_STATIC_POINT_COLOR 901
#define IDS_DLGCOLORSET_STATIC_TEMPLATE_RECT_COLOR 902
#define IDS_DLGCOLORSET_STATIC_INFO_LABEL_TEXT_COLOR 903
#define IDS_DLGCOLORSET_STATIC_REPORT_SELECT_COLOR 904
#define IDS_DLGCOLORSET_STATIC_TOLERANCE_SET_COLOR 905
#define IDS_MSG_JOB_SAVE_SUCCESSFUL     907
#define IDS_MSG_METHOD_2_ACTIVATED      908
#define IDS_MSG_METHOD_1_ACTIVATED      909
#define IDS_MSG_WAIT_DETECT_POINT       910
#define IDS_MSG_POINTS_DETECTED         911
#define IDS_MN_SETTINGS_CALIB_LENS_DISABLE_LENS_CORRECTION 912
#define IDS_STATUSBAR_CONFIG_FILE       913
#define IDS_STATUSBAR_JOB_NAME          914
#define IDS_PIXEL                       915
#define IDS_MSG_CFG_NOT_FOUND           916
#define IDS_MSG_UNABLE_TO_OPEN          917
#define IDS_MSG_GRAB_IMAGE              918
#define IDS_GRAY                        919
#define IDS_POINT1_X                    920
#define IDS_POINT1_Y                    921
#define IDS_POINT2_X                    922
#define IDS_POINT2_Y                    923
#define IDS_POINT3_X                    924
#define IDS_POINT3_Y                    925
#define IDS_POINT4_X                    926
#define IDS_POINT4_Y                    927
#define IDS_MSG_TEST_IMAGE_EXIT         928
#define IDS_MSG_JOB_DETECTION_EXIT      929
#define IDS_TOTAL_JOBS                  930
#define IDS_INSPECTION_NO               931
#define IDS_SR_NO                       932
#define IDS_TIME                        933
#define IDS_OPERATOR                    934
#define IDS_UNIT                        935
#define IDS_MSG_PDF_PAGE_CANT_CREATED   936
#define IDS_MSG_ERROR_PDF_INVALID_EXE   937
#define IDS_MSG_ERROR_PDF_FILE_NOT_FOUND 938
#define IDS_MSG_ERROR_PDF_PATH_NOT_FOUND 939
#define IDS_WORD_APP_ERROR              940
#define IDS_STATIC_DLGHEADER_COMP_NAME  941
#define IDS_STATIC_DLGHEADER_MANUAL_IP  942
#define IDS_CHK_EXPORT_DATE_TIME        943
#define IDS_DLGHEADER_CAPTION           944
#define IDS_ADDED                       945
#define IDS_TEXT                        946
#define ID_INDICATOR_ZOOM               947
#define ID_INDICATOR_CALIBFACT          948
#define ID_INDICATOR_XY_COORD           949
#define IDS_DLG_PAN_ENTRY_TRANSLATION_INTERVAL 953
#define IDS_DLG_PAN_ENTRY_CALIB_PIECE_PATTERN 954
#define IDS_DLG_PAN_ENTRY_PANNING       955
#define IDS_CAMERA_SELECTION            958
#define IDS_SELECT_CAMERA               959
#define IDS_MSG_NO_DATA_FOUND           960
#define IDS_STATIC_PREFIX_SETTINGS      962
#define IDS_DLG_UNIT_SETTINGS           963
#define IDS_STATIC_LENGTH_UNIT          964
#define IDS_STATIC_ANGLE_UNIT           965
#define IDS_RAD_ANGLE_PREFIX_AS_LENGTH  966
#define IDS_MICRON                      967
#define IDS_MSG_FILE_ALREADY_OPEN       968
#define IDS_TOLERANCE_EDIT_SETTINGS     969
#define IDS_MSG_OVERSTEP_TOL            974
#define IDS_MSG_SHAPE_NOT_FOUND         975
#define IDS_MSG_SINGLE_STEP_INSPECTION  976
#define IDS_DLGCOLORSET_STATIC_TRACKER_COLOR 977
#define IDS_DLGCOLORSET_STATIC_TRACKER__FEATURE_COLOR 978
#define IDS_DLG_CONSTRUCT_SOLUTION_SETTINGS 979
#define IDS_DLG_CONSTRUCT_LINE_SELECTION_SETTINGS 980
#define IDS_STATIC_DLGARRAY_INIT_STEP   984
#define IDS_STATIC_DLGARRAY_TERMINATE_STEP 985
#define IDS_RAD_DLGARRAY_RECT_ARRAY     986
#define IDS_RAD_DLGARRAY_CIRCULAR_ARRAY 987
#define IDS_RAD_DLGARRAY_MIRROR         988
#define IDS_RAD_DLGARRAY_TRANSLATION    989
#define IDS_RAD_DLGARRAY_Z_SHAPE        990
#define IDS_RAD_DLGARRAY_S_SHAPE        991
#define IDS_STATIC_DLGARRAY_ROW         992
#define IDS_STATIC_DLGARRAY_COLUMN      993
#define IDS_STATIC_DLGARRAY_ROW_EXCURSION 994
#define IDS_STATIC_DLGARRAY_COLUMN_EXCURSION 995
#define IDS_STATIC_DLGARRAY_BENCHMARK_COORDS 996
#define IDS_STATIC_DLGARRAY_COMMON_ELEMENTS 997
#define IDS_STATIC_ARRAY                998
#define IDS_STATIC_DLGARRAY_X_EXCURSION 1004
#define IDS_STATIC_DLGARRAY_Y_EXCURSION 1005
#define IDS_STATIC_TOTAL_OBJECTS        1006
#define IDS_RAD_DLGARRAY_LEVEL_MIRROR   1007
#define IDS_RAD_DLGARRAY_VERTICAL_MIRROR 1008
#define IDS_FILLING_ANGLE               1009
#define IDS_CHK_DLGARRAY_ROTATE_WHEN_COPY 1010
#define IDS_ELEMENT_REFERENCE           1011
#define IDS_RECTANGLE_ARRAY_NOTE        1012
#define IDS_CIRCULAR_ARRAY_NOTE         1013
#define IDS_MM                          1014
#define IDS_INCH                        1015
#define IDS_MILES                       1016
#define IDS_OUTPT_FORMAT                1020
#define IDS_STATIC_SMALLER              1021
#define IDS_STATIC_LARGER               1022
#define IDS_STATIC_EXPORT_TO_EXCEL      1023
#define IDS_STAT_COLOR_OVERSTEP_UP_TOL  1024
#define IDS_STAT_COLOR_OVERSTEP_LOW_TOL 1025
#define IDS_STATIC_TEMPLATE_EXPORT_EXCEL 1026
#define IDS_STATIC_DEGREES              1029
#define IDS_RADIANS                     1030
#define IDS_MEASUREMENT_UNIT            1031
#define IDS_TRANSLATE_DISTANCE_X        1032
#define IDS_TRANSLATE_DISTANCE_Y        1033
#define IDS_DLGINSPPARAMS_MODELPARAMS_REDUCTIONFACTOR2 1034
#define IDS_DLGINSPPARAMS_MEASPARAMS_MEASTHRESH 1035
#define IDS_RESET_TO_DEFAULT            1036
#define IDS_CORRECTION_MAP              1037
#define IDS_GENERATE                    1038
#define IDS_APPLY_MAP                   1039
#define IDS_ENABLE_MAP                  1040
#define IDS_360_SUPPLEMENTARY_ANGLE     1041
#define IDS_MEASURED_ELEMENT            1042
#define IDS_DATUM                       1043
#define IDS_DATUM_ELEMENT               1044
#define IDS_EXTENDED_TOLERENCE          1045
#define IDS_GEOTOL_PARALLEL             1052
#define IDS_GEOTOL_VERTICAL             1053
#define IDS_GEOTOL_COAXIAL              1054
#define IDS_GEOMETRIC_TOLERANCES        1055
#define IDS_REFERENCE_LENGTH            1056
#define IDS_REFERENCE_ANGLE             1057
#define IDS_DX                          1058
#define IDS_DY                          1059
#define IDS_DZ                          1060
#define IDS_TOLERANCE_RULE              1061
#define IDS_MAXIMUM_DEVIATION           1071
#define IDS_MINIMUM_DEVIATION           1072
#define IDS_ERROR_PARALLELISM           1073
#define IDS_ERROR_VERTICALITY           1074
#define IDS_ERROR_ANGULARITY            1075
#define IDS_ERROR_POSITION              1076
#define IDS_ERROR_CONCENTRICITY         1077
#define IDS_ERROR_MEASURED_ELEMENT1     1078
#define IDS_ERROR_MEASURED_ELEMENT2     1079
#define IDS_ERROR_DATUM_ELEMENT         1080
#define IDS_ERROR_REFERENCE_LENGTH      1081
#define IDS_STATIC_THRES_VALUE_CALIB    1082
#define IDS_MSG_GRID_CORNERS            1083
#define IDS_MSG_CALIBRTION_OVER_DIFFERENCE 1084
#define IDS_MSG_DXF_SIZE_LARGE          1085
#define IDS_MSG_FILE_NOT_FOUND_RESELECT 1086
#define IDS_MSG_CANT_CALCULATE_SPC      1087
#define IDS_STATIC_OKMEAS_SET_COLOR     1088
#define IDS_THEORETICAL_ANGLE           1089
#define IDS_THEORETICAL_POSITION        1090
#define IDS_BTN_IMPORT_DXF              1091
#define IDS_BTN_WRITE_TO_PROGRAM        1092
#define IDS_BTN_SAVE_IMAGE              1093
#define IDS_STATIC_POSITIVE_TOLERANCE   1094
#define IDS_STATIC_NEGATIVE_TOLERANCE   1095
#define IDS_BTN_APPLY                   1096
#define IDS_RAD_PROFILE_WITH_REFERANCE  1097
#define IDS_RAD_NO_REFERANCE_PROFILE    1098
#define IDS_STATIC_DRAWING_INTERVAL     1099
#define IDS_LOADMAP                     1104
#define IDS_CHECK_ALIGNMENT             1105
#define IDS_GENERATE_APPLY_MAP          1106
#define IDS_STATIC_START_OBJECT         1107
#define IDS_STATIC_END_OBJECT           1108
#define IDS_BTN_AUTO_PROGRAM            1109
#define IDS_CHECK_POINT                 1110
#define IDS_CHECK_CONTOUR_POINTS        1111
#define IDS_CHECK_LASER_POINT           1112
#define IDS_CHECK_LINE                  1113
#define IDS_CHECK_ROUND_KEYWAY          1114
#define IDS_CHECK_CIRCLE                1115
#define IDS_CHECK_ARC                   1116
#define IDS_BTN_AUTO_COORDINATE_LABEL   1117
#define IDS_BTN_AUTO_POSITION           1118
#define IDS_TARGET_MAP                  1119
#define IDS_AUTOMATIC_PROGRAMMING       1120
#define IDS_DRAWING_RANGE               1121
#define IDS_CORRECTION                  1122
#define IDS_STRING1123                  1123
#define IDS_TEMPLATE_MIN_AREA           1124
#define IDS_TEMPLATE_MAX_AREA           1125
#define IDS_REDUCTION_FACTOR1           1126
#define IDS_REDUCTION_FACTOR2           1127
#define IDS_RAD_PROGRAM_AUTO_DETERMINE  1129
#define IDS_RAD_FIRST_EDGE              1130
#define IDS_RAD_SECOND_EDGE             1131
#define IDS_RAD_FORCED_DENOISING        1132
#define IDS_RAD_TURNING_TOOL_LINE       1133
#define IDS_RAD_SCREW_THREAD            1134
#define IDS_RAD_ELLIPSE_ALGORITHM       1135
#define IDS_REGARDLESS_OF_COLOR         1136
#define IDS_BLACK_TO_WHITE              1137
#define IDS_WHITE_TO_BLACK              1138
#define IDS_AUTO_LINE_SOLUTION_SETTINGS 1139
#define IDS_AUTO_CIRCLE_SOLUTION_SETTINGS 1140
#define IDS_AUTO_ARC_SOLUTION_SETTINGS  1141
#define IDS_AUTO_MULTISECTION_CIRCLE_SOLUTION_SETTINGS 1142
#define IDS_AUTO_RECTANGLE_SOLUTION_SETTINGS 1143
#define IDS_AUTO_FOCUS_PARAMSNG794      1144
#define IDS_AF_MARKER                   1145
#define IDS_AF_JOB                      1146
#define IDS_AF_MARKER_HEIGHT            1147
#define IDS_AF_JOB_HEIGHT               1148
#define IDS_AF_START_X_POS              1149
#define IDS_AF_START_Y_POS              1150
#define IDS_AF_START_Z_POS              1151
#define IDS_GB_AF_COARSE                1152
#define IDS_ST_AF_COARSE_STEPS          1153
#define IDS_ST_AF_COARSE_DIFFERENCE     1154
#define IDS_GB_AF_FINE                  1155
#define IDS_ST_AF_FINE_STEPS            1156
#define IDS_ST_AF_FINE_DIFFERENCE       1157
#define IIDS_BN_TEST                    1158
#define IDS_STATIC_OK_LEVELA            1159
#define IDS_STATIC_OK_LEVELB            1160
#define IDS_STATIC_OK_LEVELC            1161
#define IDS_STATIC_OK_LEVELD            1162
#define IDS_STATIC_OK_LEVELE            1163
#define IDS_EDIT_SHAPENG                1165
#define IDS_DLG_USER_MANAGEMENT         1166
#define IDS_ADMIN                       1167
#define IDS_USER_OPERATOR               1168
#define IDS_USER_SUPERVISOR             1169
#define IDS_LIST_OF_USERS               1170
#define IDS_ADD_USER                    1171
#define IDS_DELETE_USER                 1172
#define IDS_LOGIN_ERROR                 1173
#define IDS_ADMIN_RIGHTS                1174
#define IDS_USER_NAME_ALREADY_EXIST     1175
#define IDS_USER_NAME_MAX_CHAR          1176
#define IDS_NEW_USER_CREATED            1177
#define IDS_NAME_USER                   1178
#define IDS_USER_LEVEL                  1179
#define IDS_CHANGE_PASSWORD             1180
#define IDS_OLD_PASSWORD                1181
#define IDS_NEW_PASSWORD                1182
#define IDS_CONFIRM_PASSWORD            1183
#define IDS_WRONG_USER_PASSWORD         1184
#define IDS_LOGIN_FAILED                1185
#define IDS_USER_TRIED                  1186
#define IDS_PASSWORD_CHANGED            1187
#define IDS_PREVIOUS_USED_PASSWORD      1188
#define IDS_IMAGE_SAVING_TEXT           1189
#define IDS_SAVED_IMAGE_TEXT            1190
#define IDS_ERROR_SAVING_IMAGE          1191
#define IDS_TMPLT_CREATION_IN_PROCESS   1192
#define IDS_POINT_INPUT                 1193
#define IDS_LINE_INPUT                  1194
#define IDS_ARC_CIRCLE_INPUT            1195
#define IDS_DLG_INPUT_LINE_X            1196
#define IDS_DLG_INPUT_LINE_Y            1197
#define IDS_INPUT_CALCULATE             1198
#define IDS_IMPORT                      1199
#define IDS_DLG_INPUT_LINE_X1           1200
#define IDS_DLG_INPUT_LINE_X2           1201
#define IDS_DLG_INPUT_LINE_Y1           1202
#define IDS_DLG_INPUT_LINE_Y2           1203
#define IDS_INPUT_L                     1204
#define IDS_INPUT_P                     1205
#define IDS_INPUT_C                     1206
#define IDS_DLG_INPUT_MANUAL_LENGTH     1207
#define IDS_DLG_INPUT_MANUAL_ANGLE      1208
#define IDS_DLG_INPUT_ARC_R             1209
#define IDS_DLG_INPUT_ARC_START_ANGLE   1210
#define IDS_DLG_INPUT_ARC_END_ANGLE     1211
#define IDS_INPUT_DLG_UNIT              1212
#define IDS_DLG_INPUT_MANUALLY          1213
#define IDS_LT_3D_NOTE                  1214
#define IDS_DLG_LT3D_CAPTION            1215
#define IDS_START_CALIB_PROCESS         1216
#define IDS_ADMIN_RIGHTS_CALIB          1217
#define IDS_CALIB_CIRCLE_NEEDED         1218
#define IDS_INS_PARAMS_MODIFY_RIGHTS    1219
#define IDS_OPENING_INS_PARAMS_DLG      1220
#define IDS_REDUCTION_PARAMS_NOTE       1221
#define IDS_INPUT_COORDINATE            1222
#define IDS_INPUT_DLG_ANGLE             1223
#define IDS_TERMINATIVE_STEP            1224
#define IDS_REDUCTION_FACTORS_SETTINGS  1225
#define IDS_RAD_FIT_LINE                1226
#define IDS_RAD_FIT_CIRCLE              1227
#define IDS_RAD_FIT_ARC                 1228
#define IDS_RAD_MIN_CIRCUM_CIR          1229
#define IDS_FITTING_OPTIONS             1230
#define IDS_MULTI_FIT_FUNC_INSTRUCT     1231
#define IDS_VALIDATE_AXIS_POS           1232
#define IDS_ADD_COORD_BSHIFT            1233
#define IDS_SOL_SETTINGS_CAPTION        1234
#define IDS_CHK_DEFAULT_SOL             1235
#define IDS_CALCULATE_DISTANCE          1236
#define IDS_TOLERANCE_SETTING           1237
#define IDS_SINGLE_ITEM_NAME            1238
#define IDS_SINGLE_STD_VAL              1239
#define IDS_SINGLE_UPPER_TOL            1240
#define IDS_SINGLE_LOWER_TOL            1241
#define IDS_SELECT_POINT_TO_FIT         1242
#define IDS_HARDWARE_CORRECTION         1243
#define IDS_ENABLE_BAYER_DECODER        1244
#define IDS_NO_TANGENT_AVAILABLE        1245
#define IDS_OUTOFF_BITMAP_MEMORY        1246
#define IDS_NO_BITMAP_FILE              1247
#define IDS_ACTUAL_COORDINATES_NOT_FOUND 1248
#define IDS_EXCEPTION_EXCEL_DATA        1249
#define IDS_ENSURE_MASTER_IMAGE_LOADED  1250
#define IDS_STOP_MOTION                 1251
#define IDS_NOT_PARALLEL                1252
#define IDS_TRACKER_POINT_NOT_SET       1253
#define IDS_NO_DATA_SELECTED            1254
#define IDS_MAP_GENERATION              1255
#define IDS_MAP_SAVING                  1256
#define IDS_HORIZONTAL_PIXEL_DIST       1257
#define IDS_VERTICAL_PIXEL_DIST         1258
#define IDS_ACTUAL_CEN_HORIZ            1259
#define IDS_ACTUAL_CEN_VERT             1260
#define IDS_MAPFULL_GENERATION          1261
#define IDS_MAPFULL_SAVING              1262
#define IDS_MAP_LOADED                  1263
#define IDS_MAP_FROM_FILE               1264
#define IDS_FILE_NOT_FOUND              1265
#define IDS_DELETE_CLINE                1266
#define IDS_DELETE_CPOINT               1267
#define IDS_SELECT_CIRCLE_LINE          1268
#define IDS_ST_ZAXIS_ZERO_POSITION      1269
#define IDS_DLG_CAM_SERIALCOMSETTINGS   1270
#define IDS_COMPORT                     1271
#define IDS_BAUDRATE                    1272
#define IDS_DLG_PROGRESSBAR             1273
#define IDS_ST_PROGRESS_OUT             1274
#define IDS_STATIC_OVERLAP_Y            1275
#define IDS_STATIC_STITCHING_PART_Y     1276
#define IDS_STATIC_FINETUNE_STITCH_Y    1277
#define IDS_CHK_IS_STITCHING_REQUIRED   1278
#define IDS_CAMERA_CAMERACOMPORTSETTINGS 1279
#define IDS_ADOBE_NOT_FOUND             1280
#define IDS_INSTALL_ADOBE               1281
#define IDS_ARRAY_IMPL_NOTE             1282
#define IDS_TIME_SECONDS                1282
#define IDS_DEVELOPER_MODE_ON           1283
#define IDS_STATIC_STITCHING_PART_X     1284
#define IDS_ST_MARKER_THICKNESS         1285
#define IDS_BTN_SET_REDUCTION_FACTORS   1286
#define IDS_DXF_COORD_COIN              1287
#define IDS_DXF_OPTIONS                 1288
#define IDS_PARAMETER_NOT_IN_RANGE_X    1289
#define IDS_PARAMETER_NOT_IN_RANGE_Y    1290
#define IDS_PARAMETER_NOT_IN_RANGE_Z    1291
#define IDS_SELECT_LINE_OR_ANGLE        1292
#define IDS_MOVE                        1293
#define IDS_SPECIAL_CHARACTERS_STRING   1294
#define IDS_APP_RUNNING_CHINESE         1295
#define IDS_CAMEXPERT_RUNNING_CHINESE   1296
#define IDS_SAPERAMONITOR_RUNNING_CHINESE 1297
#define IDS_STATIC_LINEAR_COMPENSATION  1298
#define IDS_NONLINEAR_COMPENSATION_SETTINGS 1299
#define IDS_COMPENSATION                1300
#define IDS_NONLINEAR_COMPENSATION      1301
#define IDS_IS_GLASS_USED               1302
#define IDS_CORRUPT_DATA_1              1303
#define IDS_CORRUPT_DATA_2              1304
#define IDS_ORIGINAL_IMAGE              1305
#define IDS_CROPPED_IMAGE               1306
#define IDS_SAVE_IMAGE_MSG              1307
#define IDS_IMAGE_1                     1310
#define IDS_IMAGE_2                     1311
#define IDS_STATIC_BOTTOM_UPPER_LIMIT   1312
#define IDS_STATIC_BOTTOM_LOWER_LIMIT   1313
#define IDS_STATIC_TOP_UPPER_LIMIT      1314
#define IDS_STATIC_TOP_LOWER_LIMIT      1315
#define IDS_SETTINGS_LIGHTBRIGHTNESSLIMITSETTINGS 1316
#define IDS_STATIC_ASK_IMAGE_NO         1317
#define IDS_DLG_UPDATE_IMAGE            1318
#define IDS_TEMPLATE_DATA_NOT_FOUND_MSG1 1319
#define IDS_TEMPLATE_DATA_NOT_FOUND_MSG2 1320
#define IDS_SHAPE_MEAS_DATA_NOT_FOUND_MSG1 1321
#define IDS_SHAPE_MEAS_DATA_NOT_FOUND_MSG2 1322
#define IDS_BEST_FOCUS_IMG              1323
#define IDS_BOTH_IMAGES_AVAILABLE       1324
#define IDS_NO_OPTION_SELECTED          1325
#define IDS_NEED_TO_CHANGE_MODEL        1326
#define IDS_X_AXIS_MOVE_SPEED_MSG       1327
#define IDS_X_AXIS_GRAB_SPEED_MSG       1328
#define IDS_X_AXIS_HOME_SPEED_MSG       1329
#define IDS_X_AXIS_JOG_SPEED_MSG        1330
#define IDS_Y_AXIS_MOVE_SPEED_MSG       1331
#define IDS_Y_AXIS_GRAB_SPEED_MSG       1332
#define IDS_Y_AXIS_HOME_SPEED_MSG       1333
#define IDS_Y_AXIS_JOG_SPEED_MSG        1334
#define IDS_Z_AXIS_MOVE_SPEED_MSG       1335
#define IDS_Z_AXIS_GRAB_SPEED_MSG       1336
#define IDS_Z_AXIS_HOME_SPEED_MSG       1337
#define IDS_Z_AXIS_JOG_SPEED_MSG        1338
#define IDS_U_AXIS_MOVE_SPEED_MSG       1339
#define IDS_U_AXIS_HOME_SPEED_MSG       1340
#define IDS_U_AXIS_JOG_SPEED_MSG        1341
#define IDS_GRAB_SPEED_MSG              1342
#define IDS_LICENSE_FILE_MSG            1343
#define IDS_DECRYPT_MSG                 1344
#define IDS_MODEL_NOT_SAVED_MSG         1345
#define IDS_ERR_FULL_MAP                1346
#define IDS_HOMING_NEEDED               1347
#define IDS_STATIC_IMG_CROPPING_HEIGHT  1348
#define IDS_ENABLE_GRAB_IMAGE_BUTTON    1349
#define IDS_RESET_ENABLE_GRAB_BUTTON_MSG 1350
#define IDS_MSG_SAVING_JOB              1352
#define IDS_MSG_SAVED_JOB               1353
#define IDS_MSG_LOADING_JOB             1354
#define IDS_MSG_LOADED_JOB              1355
#define IDS_MSG_LOADING_JOB_FAIL        1356
#define IDS_ERR_READING_GENERAL_DATA    1357
#define IDS_ERR_READING_IMG_DATA        1358
#define IDS_ERR_READING_COORDINATE_INFO 1359
#define IDS_ERR_READING_SHAPES_INFO     1360
#define IDS_ERR_READING_MEAS_INFO       1361
#define IDS_ERR_READING_TEXTLABELS_INFO 1362
#define IDS_ERR_READING_TEMPLATE_EXCEL_INFO 1363
#define IDS_ERR_READING_CONFIG_FILE     1364
#define IDS_ERR_READING_HALCON_MODEL    1365
#define IDS_MSG_SAVING_JOB_FAILED       1366
#define IDS_MSG_IMAGE_NOT_LOADED        1367
#define IDS_MSG_LOADING_MASTER_IMAGE    1368
#define IDS_MSG_LOADED_MASTER_IMAGE     1369
#define IDS_ERR_IMAGE2_NOT_SAVING       1370
#define IDS_WARNING_CHINESE_CHARACTERS  1371
#define IDS_WARNING_CHARACTER_RESTRICTION 1372
#define IDS_LOCK_OBJECT_COORDINATES     1373
#define IDS_UNLOCK_OBJECT_COORDINATES   1374
#define IDS_SPECIFY_REFERENCE_COORDINATES 1375
#define IDS_REFERENCE                   1376
#define IDS_DLG_Y_COMPENSATION          1377
#define IDS_CHK_ENABLE_Y_COMPENSATION   1378
#define IDS_LINE_TO_LINE_COMPENSATION   1379
#define IDS_LINE_TO_OTHER_COMPENSATION  1380
#define IDS_FORMULA                     1381
#define IDS_HEADER_SETTING_FORMAT_2     1382
#define IDS_ENABLE_HEADER_FORMAT        1383
#define IDS_ADD_TO_GRID                 1384
#define IDS_CLEAR_ALL_GRID              1385
#define IDS_MN_LOADCFGFILE              1386
#define IDS_MN_MATCH_CFG_COORDINATES    1387
#define IDS_SAVE_OTHER_FILES            1388
#define IDS_READ_DIMS                   1388
#define IDS_YES                         1389
#define IDS_SHOW_SHAPE_LABELS           1389
#define IDS_NO                          1390
#define IDS_MIN_CIRCLE_DIA              1390
#define IDS_JOB_NOT_SAVED_YET           1391
#define IDS_XY_OFFSETS                  1391
#define IDS_COMPANY_NAME_CH             1392
#define IDS_OFFSET_X                    1392
#define IDS_PRODUCT_PART_NUMBER_CH      1393
#define IDS_OFFSET_Y                    1393
#define IDS_PRODUCT_NAME_CH             1394
#define IDS_SELECT_SHAPES_W_DIMS        1394
#define IDS_GROUP_CODE_CH               1395
#define IDS_BTM_LIGHT                   1395
#define IDS_TYPE_CH                     1396
#define IDS_TOP_LIGHT                   1396
#define IDS_SPECIFICATION_STANDARD_CH   1397
#define IDS_MIN_LINE_LENGTH1            1397
#define IDS_UPPER_SIZE_LIMIT_CH         1398
#define IDS_MIN_LINE_LENGTH             1398
#define IDS_LOWER_SIZE_LIMIT_CH         1399
#define IDS_DEFAULT_COORDINATE          1399
#define IDS_SAMPLE_SIZE_CH              1400
#define IDS_LINE_CIRCLE_INT_OPTIONS     1400
#define IDS_ERROR_CH                    1401
#define IDS_LINE_CIRCLE_INT             1401
#define IDS_WARNING_ABOUT_IMAGE_MISMATCH 1402
#define IDS_PERP_CIRCLE_TO_LINE         1402
#define IDS_MSGBOX_C_DRIVE_NOT_ALLOWED  1403
#define IDS_CLOSEST_PT_LINE_CIRCLE      1403
#define IDS_WARNING_C_DRIVE_NOT_ALLOWED_1 1404
#define IDS_OPTIONS                     1404
#define IDS_WARNING_C_DRIVE_NOT_ALLOWED_2 1405
#define IDS_MSG_CONSTRUCT_PT_2_CIRCLES_CONDITION 1405
#define IDS_MSGBOX_ABORT_CONTINUE       1406
#define IDS_RING_THK                    1406
#define IDS_WARNING_ABORT_EDITING       1407
#define IDS_RECT_SELECT                 1407
#define IDS_WARNING_JOB_CANNOT_SAVE     1408
#define IDS_SHOW_CROSSHAIR              1408
#define IDS_HIDE_CROSSHAIR              1409
#define IDS_HIDE_DUMMY					1410

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1309
#define _APS_NEXT_COMMAND_VALUE         32937
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           370
#endif
#endif
